[build]
 
  base = "/"
  
 
  command = "npm run build"
  
  
  publish = "build"

[dev]
  
  command = "npm start"
  port = 3000

# Environment variables
[build.environment]
  NODE_ENV = "production"

# Redirects and other custom headers
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
